mavtables: Filter Class Reference
Filter Class Reference
#include <Filter.hpp>
Public Member Functions
Filter (const Filter &other)=default
Filter (Filter &&other)=default
Filter (Chain default_chain, bool accept_by_default=false)
TEST_VIRTUAL ~Filter ()=default
TEST_VIRTUAL std::pair< bool, int > will_accept (const Packet &packet, const MAVAddress &address)
Filter & operator= (const Filter &other)=default
Filter & operator= (Filter &&other)=default
Friends
bool operator== (const Filter &lhs, const Filter &rhs)
bool operator!= (const Filter &lhs, const Filter &rhs)
Detailed Description
The filter used to determine whether to accept or reject a packet.
See also
Chain
Rule
If
Definition at line 38 of file Filter.hpp.
Constructor & Destructor Documentation
Filter() [1/3]
Filter::Filter (const Filter & other) default
Copy constructor.
Parameters
other Filter to copy from.
Filter() [2/3]
Filter::Filter (Filter && other) default
Move constructor.
Parameters
other Filter to move from.
Filter() [3/3]
Filter::Filter (Chain default_chain, bool accept_by_default = false)
Construct a new packet filter.
Parameters
default_chain The Chain that all filtering begins with.
accept_by_default Whether to accept (true) or reject (false) packets that don't match any rules in the default chain or any chains called by the default chain. The default value is false and thus to reject unmatched packets.
Definition at line 36 of file Filter.cpp.
~Filter()
TEST_VIRTUAL Filter::~Filter () default
Member Function Documentation
operator=() [1/2]
Filter& Filter::operator= (const Filter & other) default
Assignment operator.
Parameters
other Filter to copy from.
operator=() [2/2]
Filter& Filter::operator= (Filter && other) default
Assignment operator (by move semantics).
Parameters
other Filter to move from.
will_accept()
std::pair< bool, int > Filter::will_accept (const Packet & packet, const MAVAddress & address)
Determine whether to accept or reject a packet/address combination.
Parameters
packet The packet to determine whether to allow or not.
address The address the packet will be sent out on if the action allows it.
Returns
A pair (tuple) with the first value being whether to accept the packet or not and the second being the priority to use when sending the packet. The second value is only defined if the first value is true (accept).
Definition at line 53 of file Filter.cpp.
References Action::ACCEPT, Chain::action(), Action::action(), Action::CONTINUE, Action::DEFAULT, Action::priority(), and Action::REJECT.
Friends And Related Function Documentation
operator!=
bool operator!= (const Filter & lhs, const Filter & rhs) friend
Inequality comparison.
The default chain and default action are compared.
Parameters
lhs The left hand side packet filter.
rhs The right hand side packet filter.
Return values
true if lhs is not the same as rhs.
false if lhs is the same as rhs.
Definition at line 102 of file Filter.cpp.
operator==
bool operator== (const Filter & lhs, const Filter & rhs) friend
Equality comparison.
The default chain and default action are compared.
Parameters
lhs The left hand side packet filter.
rhs The right hand side packet filter.
Return values
true if lhs is the same as rhs.
false if lhs is not the same as rhs.
Definition at line 85 of file Filter.cpp.
The documentation for this class was generated from the following files:
Filter.hpp
Filter.cpp