mavtables: packet_v2::Packet Class Reference
packet_v2::Packet Class Reference
#include <PacketVersion2.hpp>
Public Types
enum Version { V1 = 0x0100, V2 = 0x0200 }
Public Member Functions
Packet (const Packet &other)=default
Packet (Packet &&other)=default
Packet (std::vector< uint8_t > data)
virtual ::Packet::Version version () const
virtual unsigned long id () const
virtual std::string name () const
virtual MAVAddress source () const
virtual std::optional< MAVAddress > dest () const
Packet & operator= (const Packet &other)=default
Packet & operator= (Packet &&other)=default
void connection (std::weak_ptr< Connection > connection)
const std::shared_ptr< Connection > connection () const
const std::vector< uint8_t > & data () const
Related Functions
(Note that these are not member functions.)
bool is_signed (const std::vector< uint8_t > &data)
bool header_complete (const std::vector< uint8_t > &data)
bool packet_complete (const std::vector< uint8_t > &data)
const struct mavlink::v2_header * header (const std::vector< uint8_t > &data)
bool operator== (const Packet &lhs, const Packet &rhs)
bool operator!= (const Packet &lhs, const Packet &rhs)
std::ostream & operator<< (std::ostream &os, const Packet &packet)
Detailed Description
A MAVLink packet with the version 2 wire protocol.
Definition at line 61 of file PacketVersion2.hpp.
Member Enumeration Documentation
Version
enum Packet::Version inherited
Enumerator
V1
MAVLink Version 1.0.
V2
MAVLink Version 2.0.
Definition at line 47 of file Packet.hpp.
Constructor & Destructor Documentation
Packet() [1/3]
packet_v2::Packet::Packet (const Packet & other) default
Copy constructor.
Parameters
other Packet to copy from.
Packet() [2/3]
packet_v2::Packet::Packet (Packet && other) default
Move constructor.
Parameters
other Packet to move from.
Packet() [3/3]
Packet::Packet (std::vector< uint8_t > data)
Construct a packet.
Parameters
data Raw packet data.
Exceptions
std::invalid_argument if packet data does not start with the magic byte (0xFD).
std::length_error if packet data is either too short or too long.
Definition at line 41 of file PacketVersion2.cpp.
References packet_v2::CHECKSUM_LENGTH, Packet::data(), header(), header_complete(), packet_v2::HEADER_LENGTH, is_signed(), mavlink::v2_header::len, mavlink::v2_header::msgid, packet_complete(), packet_v2::SIGNATURE_LENGTH, and packet_v2::START_BYTE.
Member Function Documentation
connection() [1/2]
void Packet::connection (std::weak_ptr< Connection > connection) inherited
Set the source connection of the packet.
Parameters
connection The source connection.
See also
connection()
Definition at line 63 of file Packet.cpp.
References Packet::connection().
connection() [2/2]
const std::shared_ptr< Connection > Packet::connection () const inherited
Get the source connection of the packet.
Returns
The source connection if set and it still exists, otherwise nullptr.
See also
connection(std::weak_ptr<Connection>)
Definition at line 75 of file Packet.cpp.
data()
const std::vector< uint8_t > & Packet::data () const inherited
Return the packet data.
Returns
The packet data as a vector of bytes.
Definition at line 52 of file Packet.cpp.
dest()
std::optional< MAVAddress > Packet::dest () const virtual
Return destination address.
Where the packet is sent to. This is optional because not all packets have a destination. If a system is specified, but not a component, a component ID of 0 will be used (the broadcast ID).
Returns
The destination MAVLink address of the packet if not a broadcast packet. If the packet does not have a destination address then {} will be returned.
Thanks
: The mavlink-router project for an example of how to extract the destination address.
Implements Packet.
Definition at line 155 of file PacketVersion2.cpp.
References Packet::data(), and header().
id()
unsigned long Packet::id () const virtual
Return MAVLink message ID.
Returns
The numeric message ID of the MAVLink packet (0 to 255).
Implements Packet.
Definition at line 117 of file PacketVersion2.cpp.
References Packet::data(), header(), and mavlink::v2_header::msgid.
name()
std::string Packet::name () const virtual
Return MAVLink message name.
Returns
The message name of the MAVLink packet.
Exceptions
std::runtime_error If the packet data has an invalid ID.
Implements Packet.
Definition at line 127 of file PacketVersion2.cpp.
References Packet::data(), and header().
operator=() [1/2]
Packet& packet_v2::Packet::operator= (const Packet & other) default
Assignment operator.
Parameters
other Packet to copy from.
operator=() [2/2]
Packet& packet_v2::Packet::operator= (Packet && other) default
Assignment operator (by move semantics).
Parameters
other Packet to move from.
source()
MAVAddress Packet::source () const virtual
Return source address.
Where the packet came from.
Returns
The source MAVLink address of the packet.
Implements Packet.
Definition at line 144 of file PacketVersion2.cpp.
References Packet::data(), and header().
version()
Packet::Version Packet::version () const virtual
Return packet version.
Returns
Two byte Packet version with major version in MSB and minor version in LSB.
0x0200 (v2.0) - Packet::V2
Implements Packet.
Definition at line 111 of file PacketVersion2.cpp.
Friends And Related Function Documentation
header()
const struct mavlink::v2_header * header (const std::vector< uint8_t > & data) related
Cast data as a v2.0 packet header structure pointer.
Parameters
data The packet data.
Returns
A pointer to the given data, cast to a v2.0 header structure. If an incomplete header is given a nullptr will be returned.
Definition at line 289 of file PacketVersion2.cpp.
References packet_v2::header_complete().
header_complete()
bool header_complete (const std::vector< uint8_t > & data) related
Determine if the given data contains a complete v2.0 header.
Parameters
data The packet data.
Return values
true if data contains a complete header (starting with the magic byte).
false if data does not contain a complete v2.0 header.
Definition at line 247 of file PacketVersion2.cpp.
References packet_v2::HEADER_LENGTH, and packet_v2::START_BYTE.
is_signed()
bool is_signed (const std::vector< uint8_t > & data) related
Determine if a MAVLink v2.0 packet is signed or not.
Parameters
data The packet data.
Exceptions
std::invalid_argument Header is not complete or is invalid.
Definition at line 227 of file PacketVersion2.cpp.
References packet_v2::header(), and packet_v2::header_complete().
operator!=()
bool operator!= (const Packet & lhs, const Packet & rhs) related
Inequality comparison.
Compares the raw packet data.
Parameters
lhs The left hand side packet.
rhs The right hand side packet.
Return values
true if lhs and rhs do not have the same packet data.
false if lhs and rhs have the same packet data.
Definition at line 107 of file Packet.cpp.
References Packet::data().
operator<<()
std::ostream & operator<< (std::ostream & os, const Packet & packet) related
Print the packet to the given output stream.
The format is "<Message Name> (#<Message ID>) from <Source Address> to <Destination Address> (v<Packet Version>)". However, "to <Destination Address>" is optional and will not be printed if the destination is the broadcast address 0.0.
Some examples are:
HEARTBEAT (#1) from 16.8 (v1.0)
PING (#4) from 128.4 to 16.8 (v2.0)
DATA_TRANSMISSION_HANDSHAKE (#130) from 16.8 (v2.0)
ENCAPSULATED_DATA (#131) from 128.4 (v2.0)
Parameters
os The output stream to print to.
packet The MAVLink packet to print.
Returns
The output stream.
Definition at line 131 of file Packet.cpp.
References Packet::dest(), Packet::id(), Packet::name(), Packet::source(), and Packet::version().
operator==()
bool operator== (const Packet & lhs, const Packet & rhs) related
Equality comparison.
Compares the raw packet data.
Parameters
lhs The left hand side packet.
rhs The right hand side packet.
Return values
true if lhs and rhs have the same packet data.
false if lhs and rhs do not have the same packet data.
Definition at line 91 of file Packet.cpp.
References Packet::data().
packet_complete()
bool packet_complete (const std::vector< uint8_t > & data) related
Determine if the given data contains a complete v2.0 packet.
Parameters
data The packet data.
Return values
true if data contains a complete packet (starting with the magic byte).
false if data does not contain a complete v1.0 packet, or if there is extra bytes in data beyond the packet.
Definition at line 263 of file PacketVersion2.cpp.
References packet_v2::CHECKSUM_LENGTH, packet_v2::header(), packet_v2::header_complete(), packet_v2::HEADER_LENGTH, mavlink::v2_header::len, and packet_v2::SIGNATURE_LENGTH.
The documentation for this class was generated from the following files:
PacketVersion2.hpp
PacketVersion2.cpp