mavtables: Options Class Reference
Options Class Reference
#include <Options.hpp>
Public Member Functions
Options (int argc, const char *argv[], const Filesystem &filesystem=Filesystem())
bool ast ()
unsigned int loglevel ()
std::string config_file ()
bool run ()
operator bool () const
Related Functions
(Note that these are not member functions.)
std::optional< std::string > find_config (const Filesystem &filesystem)
Detailed Description
An options class which is used to parse the command line arguments.
This class is what provides the command line help for mavtables.
usage: mavtables:
-h [ --help ]         print this message
--config arg          specify configuration file
--ast                 print AST of configuration file (do not run)
--version             print version and license information
--loglevel arg        level of logging, between 0 and 3
Definition at line 42 of file Options.hpp.
Constructor & Destructor Documentation
Options()
Options::Options (int argc, const char * argv[], const Filesystem & filesystem = Filesystem())
Construct an options object.
This will parse the command line arguments and construct an object for passing the result of these arguments to the application.
The first two arguments are designed to be taken directly from the inputs to the standard main function.
Parameters
argc The number of command line arguments given.
argv The command line arguments, as given in the arguments to the main function.
filesystem A filesystem instance. The default is to construct an instance. This exists for testing purposes.
Exceptions
std::runtime_error if no configuration file can be found.
Definition at line 46 of file Options.cpp.
References config_file(), Filesystem::exists(), and find_config().
Member Function Documentation
ast()
bool Options::ast ()
Determine whether to print the configuration file's AST or not.
Return values
true Print abstract syntax tree of configuration file.
false Don't print abstract syntax tree of configuration file.
Definition at line 135 of file Options.cpp.
config_file()
std::string Options::config_file ()
Get path to an existing configuration file.
Returns
The path to an existing, but not necessarily valid configuration file.
Definition at line 146 of file Options.cpp.
loglevel()
unsigned int Options::loglevel ()
Get the log level.
Returns
The level to log at, between 0 and 3.
Definition at line 156 of file Options.cpp.
operator bool()
Options::operator bool () const explicit
Determine if the Options object is valid.
Return values
true If the options object successfully parsed the command line arguments.
false If the program should exit immediately.
Definition at line 179 of file Options.cpp.
run()
bool Options::run ()
Determine whether to run the firewall/router or not.
Return values
true Run the firewall/router.
false Don't run the firewall/router.
Definition at line 167 of file Options.cpp.
Friends And Related Function Documentation
find_config()
std::optional< std::string > find_config (const Filesystem & filesystem) related
Find the configuration file.
Find the first configuration file in the list below:
The target of the MAVTABLES_CONFIG_PATH environment variable.
.mavtablesrc in the current directory.
.mavtablesrc at $HOME/.mavtablesrc.
The main configuration file at PREFIX/etc/mavtables.conf.
Parameters
filesystem A filesystem instance. The default is to construct an instance. This exists for testing purposes.
Returns
The path to the first configuration file found. {} if no configuration file could be found.
Definition at line 199 of file Options.cpp.
References Filesystem::exists().
The documentation for this class was generated from the following files:
Options.hpp
Options.cpp