mavtables: mavtables.cpp File Reference
mavtables.cpp File Reference
#include <cstdlib>
#include <exception>
#include <iostream>
#include <string>
#include <boost/program_options.hpp>
#include "config.hpp"
#include "config_grammar.hpp"
#include "ConfigParser.hpp"
#include "Logger.hpp"
#include "Options.hpp"
#include "utility.hpp"
Functions
int main (int argc, const char *argv[])
Function Documentation
main()
int main (int argc, const char * argv[])
mavtables: A MAVLink router and firewall.
See the README for further documentation.
Definition at line 37 of file mavtables.cpp.
References Options::ast(), Options::config_file(), Logger::level(), Options::loglevel(), and Options::run().