mavtables: packet_scripter Namespace Reference
packet_scripter Namespace Reference
Functions
def send_packet (mav, packet, system=0, component=0)
def parse_line (line)
def parse_file (filename)
def start_connection (args)
def parse_args ()
def main ()
Function Documentation
main()
def packet_scripter.main ()
Definition at line 480 of file packet_scripter.py.
References parse_args(), parse_file(), send_packet(), and start_connection().
parse_args()
def packet_scripter.parse_args ()
Definition at line 458 of file packet_scripter.py.
parse_file()
def packet_scripter.parse_file (filename)
Definition at line 437 of file packet_scripter.py.
References parse_line().
parse_line()
def packet_scripter.parse_line (line)
Definition at line 426 of file packet_scripter.py.
send_packet()
def packet_scripter.send_packet (mav, packet, system = 0, component = 0)
Definition at line 16 of file packet_scripter.py.
start_connection()
def packet_scripter.start_connection (args)
Definition at line 443 of file packet_scripter.py.