mavtables: test_ConnectionFactory.cpp File Reference
test_ConnectionFactory.cpp File Reference
#include <chrono>
#include <future>
#include <memory>
#include <stdexcept>
#include <catch.hpp>
#include "ConnectionFactory.hpp"
#include "Filter.hpp"
#include "Packet.hpp"
#include "PacketVersion2.hpp"
#include "utility.hpp"
#include "common.hpp"
#include "common_Packet.hpp"
Functions
TEST_CASE ("ConnectionFactory's can be constructed.", "[ConnectionFactory]")
TEST_CASE ("ConnectionFactory's 'get' method returns a new connection.", "[ConnectionFactory]")
TEST_CASE ("ConnectionFactory's 'wait_for_packet' method waits for a packet " "on any of the connections created by the factory.", "[ConnectionFactory]")
Function Documentation
TEST_CASE() [1/3]
TEST_CASE ("ConnectionFactory's can be constructed." , "" [ConnectionFactory])
Definition at line 38 of file test_ConnectionFactory.cpp.
References mock_shared().
TEST_CASE() [2/3]
TEST_CASE ("ConnectionFactory's 'get' method returns a new connection." , "" [ConnectionFactory])
Definition at line 54 of file test_ConnectionFactory.cpp.
References logger::heartbeat(), and mock_shared().
TEST_CASE() [3/3]
TEST_CASE ("ConnectionFactory's 'wait_for_packet' method waits for a packet " "on any of the connections created by the factory." , "" [ConnectionFactory])
Definition at line 95 of file test_ConnectionFactory.cpp.
References logger::heartbeat(), and mock_shared().