mavtables: test_Action.cpp File Reference
test_Action.cpp File Reference
#include <utility>
#include <catch.hpp>
#include "Action.hpp"
#include "utility.hpp"
Functions
TEST_CASE ("Action's 'make_accept' factory method constructs an ACCEPT action.", "[Action]")
TEST_CASE ("Action's 'make_reject' factory method constructs a REJECT action.", "[Action]")
TEST_CASE ("Action's 'make_continue' factory method constructs a CONTINUE " "action.", "[Action]")
TEST_CASE ("Action's 'make_default' factory method constructs a DEFAULT action.", "[Action]")
TEST_CASE ("Action's 'priority' method sets and gets the priority.", "[Action]")
TEST_CASE ("Action's are comparable.", "[Action]")
TEST_CASE ("Action's are copyable.", "[Action]")
TEST_CASE ("Action's are movable.", "[Action]")
TEST_CASE ("Action's are assignable.", "[Action]")
TEST_CASE ("Action's are printable.")
Variables
auto action_b = Action::make_accept(100)
action_a = std::move(action_b)
Function Documentation
TEST_CASE() [1/10]
TEST_CASE ("Action's 'make_accept' factory method constructs an ACCEPT action." , "" [Action])
Definition at line 26 of file test_Action.cpp.
TEST_CASE() [2/10]
TEST_CASE ("Action's 'make_reject' factory method constructs a REJECT action." , "" [Action])
Definition at line 44 of file test_Action.cpp.
References Action::make_reject().
TEST_CASE() [3/10]
TEST_CASE ("Action's 'make_continue' factory method constructs a CONTINUE " "action." , "" [Action])
Definition at line 53 of file test_Action.cpp.
References Action::make_continue().
TEST_CASE() [4/10]
TEST_CASE ("Action's 'make_default' factory method constructs a DEFAULT action." , "" [Action])
Definition at line 62 of file test_Action.cpp.
References Action::make_default().
TEST_CASE() [5/10]
TEST_CASE ("Action's 'priority' method sets and gets the priority." , "" [Action])
Definition at line 71 of file test_Action.cpp.
TEST_CASE() [6/10]
TEST_CASE ("Action's are comparable." , "" [Action])
Definition at line 105 of file test_Action.cpp.
TEST_CASE() [7/10]
TEST_CASE ("Action's are copyable." , "" [Action])
Definition at line 130 of file test_Action.cpp.
References Action::make_accept().
TEST_CASE() [8/10]
TEST_CASE ("Action's are movable." , "" [Action])
Definition at line 138 of file test_Action.cpp.
References Action::make_accept().
TEST_CASE() [9/10]
TEST_CASE ("Action's are assignable." , "" [Action])
Definition at line 146 of file test_Action.cpp.
References action_a, action_b, and Action::make_accept().
TEST_CASE() [10/10]
TEST_CASE ("Action's are printable.")
Definition at line 166 of file test_Action.cpp.
Variable Documentation
action_a
action_a = std::move(action_b)
Definition at line 161 of file test_Action.cpp.
action_b
auto action_b = Action::make_accept(100)
Definition at line 159 of file test_Action.cpp.