mavtables: test_PacketVersion1.cpp File Reference
test_PacketVersion1.cpp File Reference
#include <memory>
#include <optional>
#include <stdexcept>
#include <utility>
#include <catch.hpp>
#include <fakeit.hpp>
#include "config.hpp"
#include "Connection.hpp"
#include "InvalidPacketIDError.hpp"
#include "MAVAddress.hpp"
#include "mavlink.hpp"
#include "PacketVersion1.hpp"
#include "utility.hpp"
#include "common.hpp"
#include "common_Packet.hpp"
Functions
TEST_CASE ("'packet_v1::header_complete' determines whether the given bytes " "at least represent a complete header.", "[packet_v1]")
TEST_CASE ("'packet_v1::header' returns a structure pointer to the given " "header data.", "[packet_v1]")
TEST_CASE ("'packet_v1::packet_complete' determines whether the given bytes " "represent a complete packet.", "[packet_v1]")
TEST_CASE ("packet_v1::Packet's can be constructed.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's are comparable.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's are copyable.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's are movable.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's are assignable.", "[Packet]")
TEST_CASE ("packet_v1::Packet's contain raw packet data and make it accessible.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's have a version.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's have an ID.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's have a name.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's have a source address.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's optionally have a destination address.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's optionally have a source connection.", "[packet_v1::Packet]")
TEST_CASE ("packet_v1::Packet's are printable.", "[packet_v1::Packet]")
Variables
packet_v1::Packet packet_b (to_vector(SetModeV1()))
packet_a = packet_b
Function Documentation
TEST_CASE() [1/16]
TEST_CASE ("'packet_v1::header_complete' determines whether the given bytes " "at least represent a complete header." , "" [packet_v1])
Definition at line 38 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [2/16]
TEST_CASE ("'packet_v1::header' returns a structure pointer to the given " "header data." , "" [packet_v1])
Definition at line 80 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [3/16]
TEST_CASE ("'packet_v1::packet_complete' determines whether the given bytes " "represent a complete packet." , "" [packet_v1])
Definition at line 154 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [4/16]
TEST_CASE ("packet_v1::Packet's can be constructed." , "" [packet_v1::Packet])
Definition at line 204 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [5/16]
TEST_CASE ("packet_v1::Packet's are comparable." , "" [packet_v1::Packet])
Definition at line 285 of file test_PacketVersion1.cpp.
TEST_CASE() [6/16]
TEST_CASE ("packet_v1::Packet's are copyable." , "" [packet_v1::Packet])
Definition at line 308 of file test_PacketVersion1.cpp.
TEST_CASE() [7/16]
TEST_CASE ("packet_v1::Packet's are movable." , "" [packet_v1::Packet])
Definition at line 316 of file test_PacketVersion1.cpp.
TEST_CASE() [8/16]
TEST_CASE ("packet_v1::Packet's are assignable." , "" [Packet])
Definition at line 324 of file test_PacketVersion1.cpp.
References packet_a, and packet_b.
TEST_CASE() [9/16]
TEST_CASE ("packet_v1::Packet's contain raw packet data and make it accessible." , "" [packet_v1::Packet])
Definition at line 344 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [10/16]
TEST_CASE ("packet_v1::Packet's have a version." , "" [packet_v1::Packet])
Definition at line 358 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [11/16]
TEST_CASE ("packet_v1::Packet's have an ID." , "" [packet_v1::Packet])
Definition at line 372 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [12/16]
TEST_CASE ("packet_v1::Packet's have a name." , "" [packet_v1::Packet])
Definition at line 385 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [13/16]
TEST_CASE ("packet_v1::Packet's have a source address." , "" [packet_v1::Packet])
Definition at line 398 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [14/16]
TEST_CASE ("packet_v1::Packet's optionally have a destination address." , "" [packet_v1::Packet])
Definition at line 412 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [15/16]
TEST_CASE ("packet_v1::Packet's optionally have a source connection." , "" [packet_v1::Packet])
Definition at line 429 of file test_PacketVersion1.cpp.
References logger::heartbeat().
TEST_CASE() [16/16]
TEST_CASE ("packet_v1::Packet's are printable." , "" [packet_v1::Packet])
Definition at line 450 of file test_PacketVersion1.cpp.
References logger::heartbeat(), and ping.
Variable Documentation
packet_a
packet_a = packet_b
Definition at line 339 of file test_PacketVersion1.cpp.
packet_b
packet_v1::Packet packet_b(to_vector(SetModeV1()))
Initial value:
{
    packet_v1::Packet packet_a(to_vector(PingV1()))