mavtables: test_UDPInterface.cpp File Reference
test_UDPInterface.cpp File Reference
#include <algorithm>
#include <chrono>
#include <cstdint>
#include <memory>
#include <set>
#include <stdexcept>
#include <utility>
#include <vector>
#include <catch.hpp>
#include <fakeit.hpp>
#include "ConnectionFactory.hpp"
#include "ConnectionPool.hpp"
#include "Filter.hpp"
#include "IPAddress.hpp"
#include "Packet.hpp"
#include "PacketVersion2.hpp"
#include "UDPInterface.hpp"
#include "UDPSocket.hpp"
#include "utility.hpp"
#include "common.hpp"
#include "common_Packet.hpp"
Functions
TEST_CASE ("UDPInterface's can be constructed.", "[UPDInterface]")
TEST_CASE ("UDPInterace's 'receive_packet' method.", "[UPDInterface]")
TEST_CASE ("UDPInterace's 'send_packet' method.", "[UPDInterface]")
TEST_CASE ("UDPInterface's are printable.", "[UDPInterface]")
TEST_CASE ("OLD TEST: UDPInterface's tests.", "[UPDInterface]")
TEST_CASE ("OLD TEST: UDPInterface's 'receive_packet' method receives one or " "more MAVLink packets.", "[UPDInterface]")
TEST_CASE ("OLD TEST: UDPInterface's 'send_packet' method sends one or more " " MAVLink packets.", "[UPDInterface]")
Function Documentation
TEST_CASE() [1/7]
TEST_CASE ("UDPInterface's can be constructed." , "" [UPDInterface])
Definition at line 47 of file test_UDPInterface.cpp.
References mock_shared(), and mock_unique().
TEST_CASE() [2/7]
TEST_CASE ("UDPInterace's 'receive_packet' method." , "" [UPDInterface])
Definition at line 94 of file test_UDPInterface.cpp.
References logger::heartbeat(), mock_shared(), and mock_unique().
TEST_CASE() [3/7]
TEST_CASE ("UDPInterace's 'send_packet' method." , "" [UPDInterface])
Definition at line 454 of file test_UDPInterface.cpp.
References logger::heartbeat(), mock_shared(), mock_unique(), and ping.
TEST_CASE() [4/7]
TEST_CASE ("UDPInterface's are printable." , "" [UDPInterface])
Definition at line 763 of file test_UDPInterface.cpp.
References mock_shared(), and mock_unique().
TEST_CASE() [5/7]
TEST_CASE ("OLD TEST: UDPInterface's tests." , "" [UPDInterface])
Definition at line 781 of file test_UDPInterface.cpp.
References logger::heartbeat(), mock_shared(), and mock_unique().
TEST_CASE() [6/7]
TEST_CASE ("OLD TEST: UDPInterface's 'receive_packet' method receives one or " "more MAVLink packets." , "" [UPDInterface])
Definition at line 815 of file test_UDPInterface.cpp.
References logger::heartbeat(), mock_shared(), and mock_unique().
TEST_CASE() [7/7]
TEST_CASE ("OLD TEST: UDPInterface's 'send_packet' method sends one or more " " MAVLink packets." , "" [UPDInterface])
Definition at line 867 of file test_UDPInterface.cpp.
References mock_shared(), and mock_unique().