mavtables: test_UDPSocket.cpp File Reference
test_UDPSocket.cpp File Reference
#include <algorithm>
#include <chrono>
#include <iterator>
#include <optional>
#include <utility>
#include <catch.hpp>
#include <fakeit.hpp>
#include "IPAddress.hpp"
#include "UDPSocket.hpp"
#include <utility.hpp>
Functions
TEST_CASE ("UDPSocket's 'send' method accepts a vector of bytes and an address.", "[UDPSocket]")
TEST_CASE ("UDPSocket's 'send' method accepts two vector iterators and an " "address.", "[UDPSocket]")
TEST_CASE ("UDPSocket's 'receive' method takes a timeout and returns a vector " "of bytes and the IP address that sent them.", "[UDPSocket]")
TEST_CASE ("UDPSocket's 'receive' method takes a back inserter and a timeout " "and returns the IP address that sent the bytes written to the " "back inserter.", "[UDPSocket]")
TEST_CASE ("UDPSocket's are printable.", "UDPSocket")
Function Documentation
TEST_CASE() [1/5]
TEST_CASE ("UDPSocket's 'send' method accepts a vector of bytes and an address." , "" [UDPSocket])
Definition at line 35 of file test_UDPSocket.cpp.
References UDPSocket::send().
TEST_CASE() [2/5]
TEST_CASE ("UDPSocket's 'send' method accepts two vector iterators and an " "address." , "" [UDPSocket])
Definition at line 64 of file test_UDPSocket.cpp.
References UDPSocket::send().
TEST_CASE() [3/5]
TEST_CASE ("UDPSocket's 'receive' method takes a timeout and returns a vector " "of bytes and the IP address that sent them." , "" [UDPSocket])
Definition at line 92 of file test_UDPSocket.cpp.
References UDPSocket::receive().
TEST_CASE() [4/5]
TEST_CASE ("UDPSocket's 'receive' method takes a back inserter and a timeout " "and returns the IP address that sent the bytes written to the " "back inserter." , "" [UDPSocket])
Definition at line 129 of file test_UDPSocket.cpp.
References UDPSocket::receive().
TEST_CASE() [5/5]
TEST_CASE ("UDPSocket's are printable." , "UDPSocket")
Definition at line 163 of file test_UDPSocket.cpp.