mavtables: test_SerialPort.cpp File Reference
test_SerialPort.cpp File Reference
#include <algorithm>
#include <chrono>
#include <iterator>
#include <optional>
#include <utility>
#include <catch.hpp>
#include <fakeit.hpp>
#include "SerialPort.hpp"
#include "utility.hpp"
Functions
TEST_CASE ("SerialPort's 'read' method takes a timeout and returns a vector " "of bytes.", "[SerialPort]")
TEST_CASE ("SerialPort's 'read' method takes a back inserter and a timeout " "writes the received bytes to the back inserter.", "[SerialPort]")
TEST_CASE ("SerialPort's 'write' method accepts a vector of bytes.", "[SerialPort]")
TEST_CASE ("SerialPort's 'write' method accepts two vector iterators", "[UDPSocket]")
TEST_CASE ("SerialPort's are printable.", "SerialPort")
Function Documentation
TEST_CASE() [1/5]
TEST_CASE ("SerialPort's 'read' method takes a timeout and returns a vector " "of bytes." , "" [SerialPort])
Definition at line 34 of file test_SerialPort.cpp.
References SerialPort::read().
TEST_CASE() [2/5]
TEST_CASE ("SerialPort's 'read' method takes a back inserter and a timeout " "writes the received bytes to the back inserter." , "" [SerialPort])
Definition at line 70 of file test_SerialPort.cpp.
References SerialPort::read().
TEST_CASE() [3/5]
TEST_CASE ("SerialPort's 'write' method accepts a vector of bytes." , "" [SerialPort])
Definition at line 100 of file test_SerialPort.cpp.
References SerialPort::write().
TEST_CASE() [4/5]
TEST_CASE ("SerialPort's 'write' method accepts two vector iterators" , "" [UDPSocket])
Definition at line 126 of file test_SerialPort.cpp.
References SerialPort::write().
TEST_CASE() [5/5]
TEST_CASE ("SerialPort's are printable." , "SerialPort")
Definition at line 152 of file test_SerialPort.cpp.