mavtables: test_ConnectionPool.cpp File Reference
test_ConnectionPool.cpp File Reference
#include <memory>
#include <catch.hpp>
#include <fakeit.hpp>
#include "Connection.hpp"
#include "ConnectionPool.hpp"
#include "Logger.hpp"
#include "PacketVersion2.hpp"
#include "utility.hpp"
#include "common.hpp"
#include "common_Packet.hpp"
Functions
TEST_CASE ("ConnectionPool's can be constructed.", "[ConnectionPool]")
TEST_CASE ("ConnectionPool's can store at least one connection and send a " "packet over it.", "[ConnectionPool]")
TEST_CASE ("ConnectionPool's can store more than one connection and send a " "packet over them.", "[ConnectionPool]")
TEST_CASE ("ConnectionPool's 'remove' method removes a connection.", "[ConnectionPool]")
TEST_CASE ("ConnectionPool's 'send' method removes connections that have " "expired.", "[ConnectionPool]")
Function Documentation
TEST_CASE() [1/5]
TEST_CASE ("ConnectionPool's can be constructed." , "" [ConnectionPool])
Definition at line 33 of file test_ConnectionPool.cpp.
TEST_CASE() [2/5]
TEST_CASE ("ConnectionPool's can store at least one connection and send a " "packet over it." , "" [ConnectionPool])
Definition at line 39 of file test_ConnectionPool.cpp.
References Logger::level(), mock_shared(), and ping.
TEST_CASE() [3/5]
TEST_CASE ("ConnectionPool's can store more than one connection and send a " "packet over them." , "" [ConnectionPool])
Definition at line 83 of file test_ConnectionPool.cpp.
References Logger::level(), mock_shared(), and ping.
TEST_CASE() [4/5]
TEST_CASE ("ConnectionPool's 'remove' method removes a connection." , "" [ConnectionPool])
Definition at line 140 of file test_ConnectionPool.cpp.
References ConnectionPool::add(), mock_shared(), ConnectionPool::remove(), and ConnectionPool::send().
TEST_CASE() [5/5]
TEST_CASE ("ConnectionPool's 'send' method removes connections that have " "expired." , "" [ConnectionPool])
Definition at line 167 of file test_ConnectionPool.cpp.
References ConnectionPool::add(), mock_shared(), and ConnectionPool::send().