mavtables: test_PacketVersion2.cpp File Reference
test_PacketVersion2.cpp File Reference
#include <memory>
#include <optional>
#include <stdexcept>
#include <utility>
#include <catch.hpp>
#include <fakeit.hpp>
#include "config.hpp"
#include "Connection.hpp"
#include "InvalidPacketIDError.hpp"
#include "MAVAddress.hpp"
#include "mavlink.hpp"
#include "PacketVersion2.hpp"
#include "utility.hpp"
#include "common.hpp"
#include "common_Packet.hpp"
Functions
TEST_CASE ("'packet_v2::header_complete' determines whether the given bytes " "at least represent a complete header.", "[packet_v2]")
TEST_CASE ("'packet_v2::header' returns a structure pointer to the given " "header data.", "[packet_v2]")
TEST_CASE ("'packet_v2::packet_complete' determines whether the given bytes " "represent a complete packet.", "[packet_v2]")
TEST_CASE ("'packet_v2::is_signed' determines whether the given bytes " "represent a signed packet.", "[packet_v2]")
TEST_CASE ("packet_v2::Packet's can be constructed.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's are comparable.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's are copyable.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's are movable.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's are assignable.", "[Packet]")
TEST_CASE ("packet_v2::Packet's contain raw packet data and make it accessible.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's have a version.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's have an ID.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's have a name.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's have a source address.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's optionally have a destination address.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's optionally have a source connection.", "[packet_v2::Packet]")
TEST_CASE ("packet_v2::Packet's are printable.", "[packet_v2::Packet]")
Variables
packet_v2::Packet packet_b (to_vector(SetModeV2()))
packet_a = packet_b
Function Documentation
TEST_CASE() [1/17]
TEST_CASE ("'packet_v2::header_complete' determines whether the given bytes " "at least represent a complete header." , "" [packet_v2])
Definition at line 38 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [2/17]
TEST_CASE ("'packet_v2::header' returns a structure pointer to the given " "header data." , "" [packet_v2])
Definition at line 94 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [3/17]
TEST_CASE ("'packet_v2::packet_complete' determines whether the given bytes " "represent a complete packet." , "" [packet_v2])
Definition at line 214 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [4/17]
TEST_CASE ("'packet_v2::is_signed' determines whether the given bytes " "represent a signed packet." , "" [packet_v2])
Definition at line 280 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [5/17]
TEST_CASE ("packet_v2::Packet's can be constructed." , "" [packet_v2::Packet])
Definition at line 346 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [6/17]
TEST_CASE ("packet_v2::Packet's are comparable." , "" [packet_v2::Packet])
Definition at line 515 of file test_PacketVersion2.cpp.
TEST_CASE() [7/17]
TEST_CASE ("packet_v2::Packet's are copyable." , "" [packet_v2::Packet])
Definition at line 544 of file test_PacketVersion2.cpp.
TEST_CASE() [8/17]
TEST_CASE ("packet_v2::Packet's are movable." , "" [packet_v2::Packet])
Definition at line 552 of file test_PacketVersion2.cpp.
TEST_CASE() [9/17]
TEST_CASE ("packet_v2::Packet's are assignable." , "" [Packet])
Definition at line 560 of file test_PacketVersion2.cpp.
References packet_a, and packet_b.
TEST_CASE() [10/17]
TEST_CASE ("packet_v2::Packet's contain raw packet data and make it accessible." , "" [packet_v2::Packet])
Definition at line 580 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [11/17]
TEST_CASE ("packet_v2::Packet's have a version." , "" [packet_v2::Packet])
Definition at line 602 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [12/17]
TEST_CASE ("packet_v2::Packet's have an ID." , "" [packet_v2::Packet])
Definition at line 620 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [13/17]
TEST_CASE ("packet_v2::Packet's have a name." , "" [packet_v2::Packet])
Definition at line 637 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [14/17]
TEST_CASE ("packet_v2::Packet's have a source address." , "" [packet_v2::Packet])
Definition at line 657 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [15/17]
TEST_CASE ("packet_v2::Packet's optionally have a destination address." , "" [packet_v2::Packet])
Definition at line 678 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
TEST_CASE() [16/17]
TEST_CASE ("packet_v2::Packet's optionally have a source connection." , "" [packet_v2::Packet])
Definition at line 703 of file test_PacketVersion2.cpp.
References logger::heartbeat().
TEST_CASE() [17/17]
TEST_CASE ("packet_v2::Packet's are printable." , "" [packet_v2::Packet])
Definition at line 724 of file test_PacketVersion2.cpp.
References logger::heartbeat(), and ping.
Variable Documentation
packet_a
packet_a = packet_b
Definition at line 575 of file test_PacketVersion2.cpp.
packet_b
packet_v2::Packet packet_b(to_vector(SetModeV2()))
Initial value:
{
    packet_v2::Packet packet_a(to_vector(PingV2()))