mavtables: test_Connection.cpp File Reference
test_Connection.cpp File Reference
#include <chrono>
#include <memory>
#include <set>
#include <stdexcept>
#include <utility>
#include <vector>
#include <catch.hpp>
#include <fakeit.hpp>
#include "AddressPool.hpp"
#include "Connection.hpp"
#include "Filter.hpp"
#include "Logger.hpp"
#include "MAVAddress.hpp"
#include "Packet.hpp"
#include "PacketQueue.hpp"
#include "PacketVersion2.hpp"
#include "utility.hpp"
#include "common.hpp"
#include "common_Packet.hpp"
Functions
TEST_CASE ("Connection's can be constructed.", "[Connection]")
TEST_CASE ("Connection's are printable", "[Connection]")
TEST_CASE ("Connection's 'add_address' method adds/updates addresses.", "[Connection]")
TEST_CASE ("Connection's 'next_packet' method.", "[Connection]")
TEST_CASE ("Connection's 'send' method ensures the given packet is not " "nullptr.", "[Connection]")
TEST_CASE ("Connection's 'send' method (with destination address).", "[Connection]")
TEST_CASE ("Connection's 'send' method (without destination address).", "[Connection]")
TEST_CASE ("Connection's 'send' method (with broadcast address 0.0).", "[Connection]")
TEST_CASE ("Connection's 'send' method (with component broadcast address x.0).", "[Connection]")
TEST_CASE ("Connection's 'send' method (destination address, system reachable, " "component unreachable.", "[Connection]")
Function Documentation
TEST_CASE() [1/10]
TEST_CASE ("Connection's can be constructed." , "" [Connection])
Definition at line 49 of file test_Connection.cpp.
References mock_shared(), and mock_unique().
TEST_CASE() [2/10]
TEST_CASE ("Connection's are printable" , "" [Connection])
Definition at line 109 of file test_Connection.cpp.
References mock_shared().
TEST_CASE() [3/10]
TEST_CASE ("Connection's 'add_address' method adds/updates addresses." , "" [Connection])
Definition at line 119 of file test_Connection.cpp.
References Logger::level(), mock_shared(), and mock_unique().
TEST_CASE() [4/10]
TEST_CASE ("Connection's 'next_packet' method." , "" [Connection])
Definition at line 183 of file test_Connection.cpp.
References mock_shared(), mock_unique(), and ping.
TEST_CASE() [5/10]
TEST_CASE ("Connection's 'send' method ensures the given packet is not " "nullptr." , "" [Connection])
Definition at line 234 of file test_Connection.cpp.
References mock_shared(), and mock_unique().
TEST_CASE() [6/10]
TEST_CASE ("Connection's 'send' method (with destination address)." , "" [Connection])
Definition at line 253 of file test_Connection.cpp.
References Logger::level(), mock_shared(), mock_unique(), and ping.
TEST_CASE() [7/10]
TEST_CASE ("Connection's 'send' method (without destination address)." , "" [Connection])
Definition at line 414 of file test_Connection.cpp.
References logger::heartbeat(), Logger::level(), mock_shared(), and mock_unique().
TEST_CASE() [8/10]
TEST_CASE ("Connection's 'send' method (with broadcast address 0.0)." , "" [Connection])
Definition at line 627 of file test_Connection.cpp.
References Logger::level(), mock_shared(), and mock_unique().
TEST_CASE() [9/10]
TEST_CASE ("Connection's 'send' method (with component broadcast address x.0)." , "" [Connection])
Definition at line 840 of file test_Connection.cpp.
References Logger::level(), mock_shared(), and mock_unique().
TEST_CASE() [10/10]
TEST_CASE ()
Definition at line 1110 of file test_Connection.cpp.
References Logger::level(), mock_shared(), mock_unique(), and ping.