mavtables: test_SerialInterface.cpp File Reference
test_SerialInterface.cpp File Reference
#include <algorithm>
#include <chrono>
#include <cstdint>
#include <set>
#include <stdexcept>
#include <vector>
#include <catch.hpp>
#include <fakeit.hpp>
#include "Connection.hpp"
#include "ConnectionPool.hpp"
#include "Packet.hpp"
#include "PacketVersion2.hpp"
#include "SerialInterface.hpp"
#include "SerialPort.hpp"
#include "utility.hpp"
#include "common.hpp"
#include "common_Packet.hpp"
Functions
TEST_CASE ("SerialInterface's can be constructed.", "[SerialInterface]")
TEST_CASE ("SerialInterface's 'receive_packet' method.", "[SerialInterface]")
TEST_CASE ("SerialInterface's 'send_packet' method.", "[SerialInterface]")
TEST_CASE ("SerialInterface's are printable.", "[SerialInterface]")
Function Documentation
TEST_CASE() [1/4]
TEST_CASE ("SerialInterface's can be constructed." , "" [SerialInterface])
Definition at line 43 of file test_SerialInterface.cpp.
References mock_shared(), and mock_unique().
TEST_CASE() [2/4]
TEST_CASE ("SerialInterface's 'receive_packet' method." , "" [SerialInterface])
Definition at line 98 of file test_SerialInterface.cpp.
References logger::heartbeat(), mock_shared(), and mock_unique().
TEST_CASE() [3/4]
TEST_CASE ("SerialInterface's 'send_packet' method." , "" [SerialInterface])
Definition at line 312 of file test_SerialInterface.cpp.
References logger::heartbeat(), mock_shared(), and mock_unique().
TEST_CASE() [4/4]
TEST_CASE ("SerialInterface's are printable." , "" [SerialInterface])
Definition at line 395 of file test_SerialInterface.cpp.
References mock_shared(), and mock_unique().