mavtables: test_Interface.cpp File Reference
test_Interface.cpp File Reference
#include <chrono>
#include <memory>
#include <catch.hpp>
#include <fakeit.hpp>
#include "ConnectionPool.hpp"
#include "Interface.hpp"
#include "Packet.hpp"
#include "PacketVersion2.hpp"
#include "utility.hpp"
#include "common.hpp"
#include "common_Packet.hpp"
Functions
TEST_CASE ("Interface's can be constructed.", "[Interface]")
TEST_CASE ("Interface's 'send_packet' method (included just for coverage)." "[Interface]")
TEST_CASE ("Interface's 'receive_packet' method sends the packet using the " "contained ConnectionPool.", "[Interface]")
TEST_CASE ("Interface's are printable.", "[Interface]")
Function Documentation
TEST_CASE() [1/4]
TEST_CASE ("Interface's can be constructed." , "" [Interface])
Definition at line 86 of file test_Interface.cpp.
References mock_shared().
TEST_CASE() [2/4]
TEST_CASE ("Interface's 'send_packet' method (included just for coverage)." "" [Interface])
Definition at line 94 of file test_Interface.cpp.
References mock_shared().
TEST_CASE() [3/4]
TEST_CASE ("Interface's 'receive_packet' method sends the packet using the " "contained ConnectionPool." , "" [Interface])
Definition at line 104 of file test_Interface.cpp.
References mock_shared().
TEST_CASE() [4/4]
TEST_CASE ("Interface's are printable." , "" [Interface])
Definition at line 119 of file test_Interface.cpp.
References mock_shared().